#!/bin/bash

# The workaround script to overcome Firebase CLI's inability
# to fetch code outside of functions folder.

# This script should be run from project root like
# ./deploy-functions

set -x
set -e

# Step 1: Build All Projects

yarn
yarn workspace functions build

# Step 2: Setup mirror folders for deployments

mkdir temp
mkdir temp/functions

# Copy Code For Deployment
cp -R functions/compiled/ temp/functions/
rm -rf functions/compiled/
echo '{
  "name": "functions",
  "private": true,
  "version": "0.1.0",
  "main": "index.js",
  "engines": {
    "node": "8"
  }
}' > temp/functions/package.json

# Copy package.json

cat firebase.json > temp/firebase.json
cat .firebaserc > temp/.firebaserc

TOKEN="$1"
PROJECT="$2"

if [ -z "$PROJECT" ]; then
  PROJECT="default"
fi

cd temp
../node_modules/.bin/firebase use "$PROJECT"
if [ -z "$TOKEN" ]; then
  ../node_modules/.bin/firebase deploy --only functions
else
  ../node_modules/.bin/firebase deploy --token=$TOKEN --non-interactive --only functions
fi

cd ../
rm -rf temp
