// flow-typed signature: d2e33542d5b490f9316c8b4755729636
// flow-typed version: <<STUB>>/react-toastify_v^4.5.2/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-toastify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-toastify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-toastify/dist/ReactToastify' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/components/CloseButton' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/components/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/components/Toast' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/components/ToastContainer' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/components/Transitions' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/index' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/toast' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/utils/constant' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/utils/cssTransition' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/utils/eventManager' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/utils/propValidator' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/components/CloseButton' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/components/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/components/Toast' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/components/ToastContainer' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/toast' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/utils/cssTransition' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/utils/eventManager' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/utils/propValidator' {
  declare module.exports: any;
}

declare module 'react-toastify/src/components/CloseButton' {
  declare module.exports: any;
}

declare module 'react-toastify/src/components/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-toastify/src/components/Toast' {
  declare module.exports: any;
}

declare module 'react-toastify/src/components/ToastContainer' {
  declare module.exports: any;
}

declare module 'react-toastify/src/components/Transitions' {
  declare module.exports: any;
}

declare module 'react-toastify/src/index' {
  declare module.exports: any;
}

declare module 'react-toastify/src/toast' {
  declare module.exports: any;
}

declare module 'react-toastify/src/utils/constant' {
  declare module.exports: any;
}

declare module 'react-toastify/src/utils/cssTransition' {
  declare module.exports: any;
}

declare module 'react-toastify/src/utils/eventManager' {
  declare module.exports: any;
}

declare module 'react-toastify/src/utils/propValidator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-toastify/dist/ReactToastify.js' {
  declare module.exports: $Exports<'react-toastify/dist/ReactToastify'>;
}
declare module 'react-toastify/lib/components/CloseButton.js' {
  declare module.exports: $Exports<'react-toastify/lib/components/CloseButton'>;
}
declare module 'react-toastify/lib/components/ProgressBar.js' {
  declare module.exports: $Exports<'react-toastify/lib/components/ProgressBar'>;
}
declare module 'react-toastify/lib/components/Toast.js' {
  declare module.exports: $Exports<'react-toastify/lib/components/Toast'>;
}
declare module 'react-toastify/lib/components/ToastContainer.js' {
  declare module.exports: $Exports<'react-toastify/lib/components/ToastContainer'>;
}
declare module 'react-toastify/lib/components/Transitions.js' {
  declare module.exports: $Exports<'react-toastify/lib/components/Transitions'>;
}
declare module 'react-toastify/lib/index.js' {
  declare module.exports: $Exports<'react-toastify/lib/index'>;
}
declare module 'react-toastify/lib/toast.js' {
  declare module.exports: $Exports<'react-toastify/lib/toast'>;
}
declare module 'react-toastify/lib/utils/constant.js' {
  declare module.exports: $Exports<'react-toastify/lib/utils/constant'>;
}
declare module 'react-toastify/lib/utils/cssTransition.js' {
  declare module.exports: $Exports<'react-toastify/lib/utils/cssTransition'>;
}
declare module 'react-toastify/lib/utils/eventManager.js' {
  declare module.exports: $Exports<'react-toastify/lib/utils/eventManager'>;
}
declare module 'react-toastify/lib/utils/propValidator.js' {
  declare module.exports: $Exports<'react-toastify/lib/utils/propValidator'>;
}
declare module 'react-toastify/src/__tests__/components/CloseButton.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/components/CloseButton'>;
}
declare module 'react-toastify/src/__tests__/components/ProgressBar.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/components/ProgressBar'>;
}
declare module 'react-toastify/src/__tests__/components/Toast.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/components/Toast'>;
}
declare module 'react-toastify/src/__tests__/components/ToastContainer.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/components/ToastContainer'>;
}
declare module 'react-toastify/src/__tests__/toast.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/toast'>;
}
declare module 'react-toastify/src/__tests__/utils/cssTransition.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/utils/cssTransition'>;
}
declare module 'react-toastify/src/__tests__/utils/eventManager.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/utils/eventManager'>;
}
declare module 'react-toastify/src/__tests__/utils/propValidator.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/utils/propValidator'>;
}
declare module 'react-toastify/src/components/CloseButton.js' {
  declare module.exports: $Exports<'react-toastify/src/components/CloseButton'>;
}
declare module 'react-toastify/src/components/ProgressBar.js' {
  declare module.exports: $Exports<'react-toastify/src/components/ProgressBar'>;
}
declare module 'react-toastify/src/components/Toast.js' {
  declare module.exports: $Exports<'react-toastify/src/components/Toast'>;
}
declare module 'react-toastify/src/components/ToastContainer.js' {
  declare module.exports: $Exports<'react-toastify/src/components/ToastContainer'>;
}
declare module 'react-toastify/src/components/Transitions.js' {
  declare module.exports: $Exports<'react-toastify/src/components/Transitions'>;
}
declare module 'react-toastify/src/index.js' {
  declare module.exports: $Exports<'react-toastify/src/index'>;
}
declare module 'react-toastify/src/toast.js' {
  declare module.exports: $Exports<'react-toastify/src/toast'>;
}
declare module 'react-toastify/src/utils/constant.js' {
  declare module.exports: $Exports<'react-toastify/src/utils/constant'>;
}
declare module 'react-toastify/src/utils/cssTransition.js' {
  declare module.exports: $Exports<'react-toastify/src/utils/cssTransition'>;
}
declare module 'react-toastify/src/utils/eventManager.js' {
  declare module.exports: $Exports<'react-toastify/src/utils/eventManager'>;
}
declare module 'react-toastify/src/utils/propValidator.js' {
  declare module.exports: $Exports<'react-toastify/src/utils/propValidator'>;
}
