// flow-typed signature: 0f2440ea6dc19aab090ec74fef1d0bde
// flow-typed version: <<STUB>>/app-manifest-webpack-plugin_v^1.2.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'app-manifest-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'app-manifest-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'app-manifest-webpack-plugin/lib/cache' {
  declare module.exports: any;
}

declare module 'app-manifest-webpack-plugin/lib/compiler' {
  declare module.exports: any;
}

declare module 'app-manifest-webpack-plugin/lib/favicons' {
  declare module.exports: any;
}

// Filename aliases
declare module 'app-manifest-webpack-plugin/index' {
  declare module.exports: $Exports<'app-manifest-webpack-plugin'>;
}
declare module 'app-manifest-webpack-plugin/index.js' {
  declare module.exports: $Exports<'app-manifest-webpack-plugin'>;
}
declare module 'app-manifest-webpack-plugin/lib/cache.js' {
  declare module.exports: $Exports<'app-manifest-webpack-plugin/lib/cache'>;
}
declare module 'app-manifest-webpack-plugin/lib/compiler.js' {
  declare module.exports: $Exports<'app-manifest-webpack-plugin/lib/compiler'>;
}
declare module 'app-manifest-webpack-plugin/lib/favicons.js' {
  declare module.exports: $Exports<'app-manifest-webpack-plugin/lib/favicons'>;
}
