// flow-typed signature: 11bdce6a1e1325e6b4ab20ecc9e11c4c
// flow-typed version: <<STUB>>/html-webpack-plugin_v^4.0.0-beta.5/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-webpack-plugin/lib/chunksorter' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/lib/compiler' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/lib/errors' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/lib/hooks' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/lib/html-tags' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/lib/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-webpack-plugin/index' {
  declare module.exports: $Exports<'html-webpack-plugin'>;
}
declare module 'html-webpack-plugin/index.js' {
  declare module.exports: $Exports<'html-webpack-plugin'>;
}
declare module 'html-webpack-plugin/lib/chunksorter.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/chunksorter'>;
}
declare module 'html-webpack-plugin/lib/compiler.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/compiler'>;
}
declare module 'html-webpack-plugin/lib/errors.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/errors'>;
}
declare module 'html-webpack-plugin/lib/hooks.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/hooks'>;
}
declare module 'html-webpack-plugin/lib/html-tags.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/html-tags'>;
}
declare module 'html-webpack-plugin/lib/loader.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/loader'>;
}
