// flow-typed signature: 37b287465aa80e668533a1f17fb9ab0c
// flow-typed version: <<STUB>>/react-calendar_v^2.18.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-calendar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-calendar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-calendar/dist/Calendar' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/Calendar/__tests__/Navigation' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/Calendar/Navigation' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/CenturyView' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/CenturyView/__tests__/Decade' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/CenturyView/Decade' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/CenturyView/Decades' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/DecadeView' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/DecadeView/__tests__/Year' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/DecadeView/Year' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/DecadeView/Years' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/entry' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/entry.nostyle' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/Flex' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/MonthView' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/MonthView/__tests__/Day' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/MonthView/__tests__/Weekdays' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/MonthView/__tests__/WeekNumbers' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/MonthView/Day' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/MonthView/Days' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/MonthView/Weekdays' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/MonthView/WeekNumber' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/MonthView/WeekNumbers' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/shared/__tests__/dateFormatter' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/shared/__tests__/dates' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/shared/__tests__/utils' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/shared/dateFormatter' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/shared/dates' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/shared/propTypes' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/shared/utils' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/Tile' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/TileGroup' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/YearView' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/YearView/__tests__/Month' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/YearView/Month' {
  declare module.exports: any;
}

declare module 'react-calendar/dist/YearView/Months' {
  declare module.exports: any;
}

declare module 'react-calendar/src/__tests__/Calendar' {
  declare module.exports: any;
}

declare module 'react-calendar/src/__tests__/CenturyView' {
  declare module.exports: any;
}

declare module 'react-calendar/src/__tests__/DecadeView' {
  declare module.exports: any;
}

declare module 'react-calendar/src/__tests__/Flex' {
  declare module.exports: any;
}

declare module 'react-calendar/src/__tests__/MonthView' {
  declare module.exports: any;
}

declare module 'react-calendar/src/__tests__/YearView' {
  declare module.exports: any;
}

declare module 'react-calendar/src/Calendar' {
  declare module.exports: any;
}

declare module 'react-calendar/src/Calendar/__tests__/Navigation' {
  declare module.exports: any;
}

declare module 'react-calendar/src/Calendar/Navigation' {
  declare module.exports: any;
}

declare module 'react-calendar/src/CenturyView' {
  declare module.exports: any;
}

declare module 'react-calendar/src/CenturyView/__tests__/Decade' {
  declare module.exports: any;
}

declare module 'react-calendar/src/CenturyView/Decade' {
  declare module.exports: any;
}

declare module 'react-calendar/src/CenturyView/Decades' {
  declare module.exports: any;
}

declare module 'react-calendar/src/DecadeView' {
  declare module.exports: any;
}

declare module 'react-calendar/src/DecadeView/__tests__/Year' {
  declare module.exports: any;
}

declare module 'react-calendar/src/DecadeView/Year' {
  declare module.exports: any;
}

declare module 'react-calendar/src/DecadeView/Years' {
  declare module.exports: any;
}

declare module 'react-calendar/src/entry' {
  declare module.exports: any;
}

declare module 'react-calendar/src/entry.nostyle' {
  declare module.exports: any;
}

declare module 'react-calendar/src/Flex' {
  declare module.exports: any;
}

declare module 'react-calendar/src/MonthView' {
  declare module.exports: any;
}

declare module 'react-calendar/src/MonthView/__tests__/Day' {
  declare module.exports: any;
}

declare module 'react-calendar/src/MonthView/__tests__/Weekdays' {
  declare module.exports: any;
}

declare module 'react-calendar/src/MonthView/__tests__/WeekNumbers' {
  declare module.exports: any;
}

declare module 'react-calendar/src/MonthView/Day' {
  declare module.exports: any;
}

declare module 'react-calendar/src/MonthView/Days' {
  declare module.exports: any;
}

declare module 'react-calendar/src/MonthView/Weekdays' {
  declare module.exports: any;
}

declare module 'react-calendar/src/MonthView/WeekNumber' {
  declare module.exports: any;
}

declare module 'react-calendar/src/MonthView/WeekNumbers' {
  declare module.exports: any;
}

declare module 'react-calendar/src/shared/__tests__/dateFormatter' {
  declare module.exports: any;
}

declare module 'react-calendar/src/shared/__tests__/dates' {
  declare module.exports: any;
}

declare module 'react-calendar/src/shared/__tests__/utils' {
  declare module.exports: any;
}

declare module 'react-calendar/src/shared/dateFormatter' {
  declare module.exports: any;
}

declare module 'react-calendar/src/shared/dates' {
  declare module.exports: any;
}

declare module 'react-calendar/src/shared/propTypes' {
  declare module.exports: any;
}

declare module 'react-calendar/src/shared/utils' {
  declare module.exports: any;
}

declare module 'react-calendar/src/Tile' {
  declare module.exports: any;
}

declare module 'react-calendar/src/TileGroup' {
  declare module.exports: any;
}

declare module 'react-calendar/src/YearView' {
  declare module.exports: any;
}

declare module 'react-calendar/src/YearView/__tests__/Month' {
  declare module.exports: any;
}

declare module 'react-calendar/src/YearView/Month' {
  declare module.exports: any;
}

declare module 'react-calendar/src/YearView/Months' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-calendar/dist/Calendar.js' {
  declare module.exports: $Exports<'react-calendar/dist/Calendar'>;
}
declare module 'react-calendar/dist/Calendar/__tests__/Navigation.js' {
  declare module.exports: $Exports<'react-calendar/dist/Calendar/__tests__/Navigation'>;
}
declare module 'react-calendar/dist/Calendar/Navigation.js' {
  declare module.exports: $Exports<'react-calendar/dist/Calendar/Navigation'>;
}
declare module 'react-calendar/dist/CenturyView.js' {
  declare module.exports: $Exports<'react-calendar/dist/CenturyView'>;
}
declare module 'react-calendar/dist/CenturyView/__tests__/Decade.js' {
  declare module.exports: $Exports<'react-calendar/dist/CenturyView/__tests__/Decade'>;
}
declare module 'react-calendar/dist/CenturyView/Decade.js' {
  declare module.exports: $Exports<'react-calendar/dist/CenturyView/Decade'>;
}
declare module 'react-calendar/dist/CenturyView/Decades.js' {
  declare module.exports: $Exports<'react-calendar/dist/CenturyView/Decades'>;
}
declare module 'react-calendar/dist/DecadeView.js' {
  declare module.exports: $Exports<'react-calendar/dist/DecadeView'>;
}
declare module 'react-calendar/dist/DecadeView/__tests__/Year.js' {
  declare module.exports: $Exports<'react-calendar/dist/DecadeView/__tests__/Year'>;
}
declare module 'react-calendar/dist/DecadeView/Year.js' {
  declare module.exports: $Exports<'react-calendar/dist/DecadeView/Year'>;
}
declare module 'react-calendar/dist/DecadeView/Years.js' {
  declare module.exports: $Exports<'react-calendar/dist/DecadeView/Years'>;
}
declare module 'react-calendar/dist/entry.js' {
  declare module.exports: $Exports<'react-calendar/dist/entry'>;
}
declare module 'react-calendar/dist/entry.nostyle.js' {
  declare module.exports: $Exports<'react-calendar/dist/entry.nostyle'>;
}
declare module 'react-calendar/dist/Flex.js' {
  declare module.exports: $Exports<'react-calendar/dist/Flex'>;
}
declare module 'react-calendar/dist/MonthView.js' {
  declare module.exports: $Exports<'react-calendar/dist/MonthView'>;
}
declare module 'react-calendar/dist/MonthView/__tests__/Day.js' {
  declare module.exports: $Exports<'react-calendar/dist/MonthView/__tests__/Day'>;
}
declare module 'react-calendar/dist/MonthView/__tests__/Weekdays.js' {
  declare module.exports: $Exports<'react-calendar/dist/MonthView/__tests__/Weekdays'>;
}
declare module 'react-calendar/dist/MonthView/__tests__/WeekNumbers.js' {
  declare module.exports: $Exports<'react-calendar/dist/MonthView/__tests__/WeekNumbers'>;
}
declare module 'react-calendar/dist/MonthView/Day.js' {
  declare module.exports: $Exports<'react-calendar/dist/MonthView/Day'>;
}
declare module 'react-calendar/dist/MonthView/Days.js' {
  declare module.exports: $Exports<'react-calendar/dist/MonthView/Days'>;
}
declare module 'react-calendar/dist/MonthView/Weekdays.js' {
  declare module.exports: $Exports<'react-calendar/dist/MonthView/Weekdays'>;
}
declare module 'react-calendar/dist/MonthView/WeekNumber.js' {
  declare module.exports: $Exports<'react-calendar/dist/MonthView/WeekNumber'>;
}
declare module 'react-calendar/dist/MonthView/WeekNumbers.js' {
  declare module.exports: $Exports<'react-calendar/dist/MonthView/WeekNumbers'>;
}
declare module 'react-calendar/dist/shared/__tests__/dateFormatter.js' {
  declare module.exports: $Exports<'react-calendar/dist/shared/__tests__/dateFormatter'>;
}
declare module 'react-calendar/dist/shared/__tests__/dates.js' {
  declare module.exports: $Exports<'react-calendar/dist/shared/__tests__/dates'>;
}
declare module 'react-calendar/dist/shared/__tests__/utils.js' {
  declare module.exports: $Exports<'react-calendar/dist/shared/__tests__/utils'>;
}
declare module 'react-calendar/dist/shared/dateFormatter.js' {
  declare module.exports: $Exports<'react-calendar/dist/shared/dateFormatter'>;
}
declare module 'react-calendar/dist/shared/dates.js' {
  declare module.exports: $Exports<'react-calendar/dist/shared/dates'>;
}
declare module 'react-calendar/dist/shared/propTypes.js' {
  declare module.exports: $Exports<'react-calendar/dist/shared/propTypes'>;
}
declare module 'react-calendar/dist/shared/utils.js' {
  declare module.exports: $Exports<'react-calendar/dist/shared/utils'>;
}
declare module 'react-calendar/dist/Tile.js' {
  declare module.exports: $Exports<'react-calendar/dist/Tile'>;
}
declare module 'react-calendar/dist/TileGroup.js' {
  declare module.exports: $Exports<'react-calendar/dist/TileGroup'>;
}
declare module 'react-calendar/dist/YearView.js' {
  declare module.exports: $Exports<'react-calendar/dist/YearView'>;
}
declare module 'react-calendar/dist/YearView/__tests__/Month.js' {
  declare module.exports: $Exports<'react-calendar/dist/YearView/__tests__/Month'>;
}
declare module 'react-calendar/dist/YearView/Month.js' {
  declare module.exports: $Exports<'react-calendar/dist/YearView/Month'>;
}
declare module 'react-calendar/dist/YearView/Months.js' {
  declare module.exports: $Exports<'react-calendar/dist/YearView/Months'>;
}
declare module 'react-calendar/src/__tests__/Calendar.jsx' {
  declare module.exports: $Exports<'react-calendar/src/__tests__/Calendar'>;
}
declare module 'react-calendar/src/__tests__/CenturyView.jsx' {
  declare module.exports: $Exports<'react-calendar/src/__tests__/CenturyView'>;
}
declare module 'react-calendar/src/__tests__/DecadeView.jsx' {
  declare module.exports: $Exports<'react-calendar/src/__tests__/DecadeView'>;
}
declare module 'react-calendar/src/__tests__/Flex.jsx' {
  declare module.exports: $Exports<'react-calendar/src/__tests__/Flex'>;
}
declare module 'react-calendar/src/__tests__/MonthView.jsx' {
  declare module.exports: $Exports<'react-calendar/src/__tests__/MonthView'>;
}
declare module 'react-calendar/src/__tests__/YearView.jsx' {
  declare module.exports: $Exports<'react-calendar/src/__tests__/YearView'>;
}
declare module 'react-calendar/src/Calendar.jsx' {
  declare module.exports: $Exports<'react-calendar/src/Calendar'>;
}
declare module 'react-calendar/src/Calendar/__tests__/Navigation.jsx' {
  declare module.exports: $Exports<'react-calendar/src/Calendar/__tests__/Navigation'>;
}
declare module 'react-calendar/src/Calendar/Navigation.jsx' {
  declare module.exports: $Exports<'react-calendar/src/Calendar/Navigation'>;
}
declare module 'react-calendar/src/CenturyView.jsx' {
  declare module.exports: $Exports<'react-calendar/src/CenturyView'>;
}
declare module 'react-calendar/src/CenturyView/__tests__/Decade.jsx' {
  declare module.exports: $Exports<'react-calendar/src/CenturyView/__tests__/Decade'>;
}
declare module 'react-calendar/src/CenturyView/Decade.jsx' {
  declare module.exports: $Exports<'react-calendar/src/CenturyView/Decade'>;
}
declare module 'react-calendar/src/CenturyView/Decades.jsx' {
  declare module.exports: $Exports<'react-calendar/src/CenturyView/Decades'>;
}
declare module 'react-calendar/src/DecadeView.jsx' {
  declare module.exports: $Exports<'react-calendar/src/DecadeView'>;
}
declare module 'react-calendar/src/DecadeView/__tests__/Year.jsx' {
  declare module.exports: $Exports<'react-calendar/src/DecadeView/__tests__/Year'>;
}
declare module 'react-calendar/src/DecadeView/Year.jsx' {
  declare module.exports: $Exports<'react-calendar/src/DecadeView/Year'>;
}
declare module 'react-calendar/src/DecadeView/Years.jsx' {
  declare module.exports: $Exports<'react-calendar/src/DecadeView/Years'>;
}
declare module 'react-calendar/src/entry.js' {
  declare module.exports: $Exports<'react-calendar/src/entry'>;
}
declare module 'react-calendar/src/entry.nostyle.js' {
  declare module.exports: $Exports<'react-calendar/src/entry.nostyle'>;
}
declare module 'react-calendar/src/Flex.jsx' {
  declare module.exports: $Exports<'react-calendar/src/Flex'>;
}
declare module 'react-calendar/src/MonthView.jsx' {
  declare module.exports: $Exports<'react-calendar/src/MonthView'>;
}
declare module 'react-calendar/src/MonthView/__tests__/Day.jsx' {
  declare module.exports: $Exports<'react-calendar/src/MonthView/__tests__/Day'>;
}
declare module 'react-calendar/src/MonthView/__tests__/Weekdays.jsx' {
  declare module.exports: $Exports<'react-calendar/src/MonthView/__tests__/Weekdays'>;
}
declare module 'react-calendar/src/MonthView/__tests__/WeekNumbers.jsx' {
  declare module.exports: $Exports<'react-calendar/src/MonthView/__tests__/WeekNumbers'>;
}
declare module 'react-calendar/src/MonthView/Day.jsx' {
  declare module.exports: $Exports<'react-calendar/src/MonthView/Day'>;
}
declare module 'react-calendar/src/MonthView/Days.jsx' {
  declare module.exports: $Exports<'react-calendar/src/MonthView/Days'>;
}
declare module 'react-calendar/src/MonthView/Weekdays.jsx' {
  declare module.exports: $Exports<'react-calendar/src/MonthView/Weekdays'>;
}
declare module 'react-calendar/src/MonthView/WeekNumber.jsx' {
  declare module.exports: $Exports<'react-calendar/src/MonthView/WeekNumber'>;
}
declare module 'react-calendar/src/MonthView/WeekNumbers.jsx' {
  declare module.exports: $Exports<'react-calendar/src/MonthView/WeekNumbers'>;
}
declare module 'react-calendar/src/shared/__tests__/dateFormatter.js' {
  declare module.exports: $Exports<'react-calendar/src/shared/__tests__/dateFormatter'>;
}
declare module 'react-calendar/src/shared/__tests__/dates.js' {
  declare module.exports: $Exports<'react-calendar/src/shared/__tests__/dates'>;
}
declare module 'react-calendar/src/shared/__tests__/utils.js' {
  declare module.exports: $Exports<'react-calendar/src/shared/__tests__/utils'>;
}
declare module 'react-calendar/src/shared/dateFormatter.js' {
  declare module.exports: $Exports<'react-calendar/src/shared/dateFormatter'>;
}
declare module 'react-calendar/src/shared/dates.js' {
  declare module.exports: $Exports<'react-calendar/src/shared/dates'>;
}
declare module 'react-calendar/src/shared/propTypes.js' {
  declare module.exports: $Exports<'react-calendar/src/shared/propTypes'>;
}
declare module 'react-calendar/src/shared/utils.js' {
  declare module.exports: $Exports<'react-calendar/src/shared/utils'>;
}
declare module 'react-calendar/src/Tile.jsx' {
  declare module.exports: $Exports<'react-calendar/src/Tile'>;
}
declare module 'react-calendar/src/TileGroup.jsx' {
  declare module.exports: $Exports<'react-calendar/src/TileGroup'>;
}
declare module 'react-calendar/src/YearView.jsx' {
  declare module.exports: $Exports<'react-calendar/src/YearView'>;
}
declare module 'react-calendar/src/YearView/__tests__/Month.jsx' {
  declare module.exports: $Exports<'react-calendar/src/YearView/__tests__/Month'>;
}
declare module 'react-calendar/src/YearView/Month.jsx' {
  declare module.exports: $Exports<'react-calendar/src/YearView/Month'>;
}
declare module 'react-calendar/src/YearView/Months.jsx' {
  declare module.exports: $Exports<'react-calendar/src/YearView/Months'>;
}
