// flow-typed signature: 259ddde83cdb5f2c6315354b2720c72b
// flow-typed version: <<STUB>>/react-search-box_v^2.0.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-search-box'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-search-box' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-search-box/dist/index.es' {
  declare module.exports: any;
}

declare module 'react-search-box/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-search-box/dist/index.es.js' {
  declare module.exports: $Exports<'react-search-box/dist/index.es'>;
}
declare module 'react-search-box/dist/index.js' {
  declare module.exports: $Exports<'react-search-box/dist/index'>;
}
