// flow-typed signature: f6c697269e273ec293b596300a6a04a0
// flow-typed version: <<STUB>>/react-live-clock_v^3.0.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-live-clock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-live-clock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-live-clock/build/react-live-clock' {
  declare module.exports: any;
}

declare module 'react-live-clock/build/react-live-clock.min' {
  declare module.exports: any;
}

declare module 'react-live-clock/cli' {
  declare module.exports: any;
}

declare module 'react-live-clock/example/bundle' {
  declare module.exports: any;
}

declare module 'react-live-clock/lib/Component' {
  declare module.exports: any;
}

declare module 'react-live-clock/lib/index' {
  declare module.exports: any;
}

declare module 'react-live-clock/lib/ReactLiveClock' {
  declare module.exports: any;
}

declare module 'react-live-clock/package-scripts' {
  declare module.exports: any;
}

declare module 'react-live-clock/src/Component' {
  declare module.exports: any;
}

declare module 'react-live-clock/src/example/App/index' {
  declare module.exports: any;
}

declare module 'react-live-clock/src/example/Example' {
  declare module.exports: any;
}

declare module 'react-live-clock/src/index' {
  declare module.exports: any;
}

declare module 'react-live-clock/src/ReactLiveClock' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-live-clock/build/react-live-clock.js' {
  declare module.exports: $Exports<'react-live-clock/build/react-live-clock'>;
}
declare module 'react-live-clock/build/react-live-clock.min.js' {
  declare module.exports: $Exports<'react-live-clock/build/react-live-clock.min'>;
}
declare module 'react-live-clock/cli.js' {
  declare module.exports: $Exports<'react-live-clock/cli'>;
}
declare module 'react-live-clock/example/bundle.js' {
  declare module.exports: $Exports<'react-live-clock/example/bundle'>;
}
declare module 'react-live-clock/lib/Component.js' {
  declare module.exports: $Exports<'react-live-clock/lib/Component'>;
}
declare module 'react-live-clock/lib/index.js' {
  declare module.exports: $Exports<'react-live-clock/lib/index'>;
}
declare module 'react-live-clock/lib/ReactLiveClock.js' {
  declare module.exports: $Exports<'react-live-clock/lib/ReactLiveClock'>;
}
declare module 'react-live-clock/package-scripts.js' {
  declare module.exports: $Exports<'react-live-clock/package-scripts'>;
}
declare module 'react-live-clock/src/Component.js' {
  declare module.exports: $Exports<'react-live-clock/src/Component'>;
}
declare module 'react-live-clock/src/example/App/index.js' {
  declare module.exports: $Exports<'react-live-clock/src/example/App/index'>;
}
declare module 'react-live-clock/src/example/Example.js' {
  declare module.exports: $Exports<'react-live-clock/src/example/Example'>;
}
declare module 'react-live-clock/src/index.js' {
  declare module.exports: $Exports<'react-live-clock/src/index'>;
}
declare module 'react-live-clock/src/ReactLiveClock.js' {
  declare module.exports: $Exports<'react-live-clock/src/ReactLiveClock'>;
}
