#!/bin/bash

set -x # Turn this on to debug

### Dependencies
### - JDK 11+
### - Node.js 10+

# Outcome: produce a JSON file fa20-courses.json with all the courses in FA20.
function createCourseInfoJson() {
    git clone https://github.com/cornell-dti/cornell-api-libs.git
    cd cornell-api-libs
    ./gradlew build -x test
    cd ../
    java -jar cornell-api-libs/build/libs/cornell-api-libs-0.5-all.jar \
        print-all-courses-in FA20 | yarn --silent simplify >./fa20-courses.json
    rm -rf cornell-api-libs
}

# Outcome: produce a single JSON file that has course and exam info.
function mergeJson() {
    yarn --silent merge
}

# Outcome: Cleanup all the intermediate json files.
function cleanup() {
    rm fa20-courses.json
}

# Comment out those parts you don't need

createCourseInfoJson
mergeJson
cleanup
