#!/bin/bash

set -x # Turn this on to debug

### Dependencies
### - JDK 11+
### - Node.js 10+

# Outcome: produce a JSON file sp19-courses.json with all the courses in SP19.
function createCourseInfoJson() {
    git clone https://github.com/cornell-dti/cornell-api-libs.git
    cd cornell-api-libs
    ./gradlew build -x test
    cd ../
    java -jar cornell-api-libs/build/libs/cornell-api-libs-0.5-all.jar \
        print-all-courses-in SP20 | node simplify-json.js >./sp20-courses.json
    rm -rf cornell-api-libs
}

# Outcome: produce JSON files final-exams.json and prelim-exams.json.
function createExamInfoJson() {
    node fetch-exam.js
}

# Outcome: produce a single JSON file that has course and exam info.
function mergeJson() {
    node merge-json.js
}

# Outcome: Cleanup all the intermediate json files.
function cleanup() {
    rm sp20-courses.json
    rm final-exams.json
    rm prelim-exams.json
}

# Comment out those parts you don't need

createCourseInfoJson
createExamInfoJson
mergeJson
cleanup
