// eslint-disable-next-line import/prefer-default-export
export type IconName =
  | 'alert'
  | 'calendar-dark'
  | 'calendar-light'
  | 'checked-dark'
  | 'checked-light'
  | 'clock'
  | 'grabber'
  | 'hide'
  | 'pin-dark-filled'
  | 'pin-dark-outline'
  | 'pin-light-filled'
  | 'pin-light-outline'
  | 'settings'
  | 'show'
  | 'tag'
  | 'unchecked'
  | 'dropdown'
  | 'x-dark'
  | 'x-light';
